spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.security.jwt.secret=${APP_SECURITY_JWT_SECRET}
app.security.refresh.secure-cookie=${APP_SECURITY_REFRESH_SECURE_COOKIE:true}
app.security.cors.allowed-origins=${APP_SECURITY_CORS_ALLOWED_ORIGINS}
